### ISSUE TITLE
Enter all IHO publications

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-iho#1]
Bibliographic data at IHO are available at:

B-series:
* English: https://iho.int/en/bathymetric-publications
* French: https://iho.int/fr/publications-bathym-triques

C-series:
* English: https://iho.int/en/capacity-building-publications
* French: https://iho.int/fr/publications-sur-le-renforcement-des-capacit-s

M-series:
* English: https://iho.int/en/miscellaneous-publications
* French: https://iho.int/fr/publications-mixtes

P-series:
* English: https://iho.int/en/periodic-publications
* French: https://iho.int/fr/publications-p-riodiques

S-series:
* English: https://iho.int/en/standards-and-specifications
* French: https://iho.int/fr/normes-et-specifications

drafts:
* English: https://iho.int/en/draft-publications
* French: https://iho.int/fr/projets-de-publications

**Comment by ronaldtse** [comment]
I have entered b-12 and s-63.

**Comment by ronaldtse** [comment]
@Darkod55 entered s-4.

**Comment by ronaldtse** [comment]
@Darkod55 entered all S-series.

**Comment by ronaldtse** [comment]
Missing:
- M-10
- B- 1,4,6,7,8,9,10
- P- 1 5 6 7
- S- 97, 98

**Comment by Darkod55** [comment]
Missing files added.
Files remaining:

b-1 - no file, only email link
b-4 - it is a map link - https://maps.ngdc.noaa.gov/viewers/bathymetry/
b-7 - no link, it says publication removed
b-8 - it is a map link - https://www.ngdc.noaa.gov/gazetteer/
b-9 - link to atlas. not sure what to do here - https://www.gebco.net/data_and_products/gebco_digital_atlas/
b-10 - link to GEBCo page, not sure what to do here - https://www.gebco.net/data_and_products/history_of_gebco/

**Comment by ronaldtse** [comment]
@Darkod55 the remaining files should be done the same way.

b-1 and b-7, just enter with available information (use this page for access link: https://iho.int/en/bathymetric-publications, type HTML)
b-4, 8, 9, 10 Instead of PDF, you can mark them as "website".

**Comment by ronaldtse** [comment]
All done in #10 . Thanks @Darkod55 !
