### ISSUE TITLE
S-44 reference should provide Ed 6

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-iho#16]
From @iho-ohi @hasel001:

> S-44, for instance, links to (in Section 1). The PDF version generates with Ed. 5 details, and I believe we should be on Ed. 6.

We are currently missing Ed 6 of S-44. We need to find a good way to find that and build on.

This also means we need to update Relaton-IHO to accept Edition numbers for citation purposes.

**Comment by ronaldtse** [comment]
This also means we need to update Relaton-IHO to accept Edition numbers for citation purposes.

**Comment by andrew2net** [comment]
implemented in https://github.com/relaton/relaton-iho/issues/16
