### ISSUE TITLE
What is the edition number of S-53 (and similar documents)?

### ISSUE THREAD

**Issue by manuelfuenmayor** [relaton/relaton-data-iho#24]
*Issue found in https://github.com/relaton/relaton-data-iho/pull/23*

For S-53 standard (and other publications) the indicated document edition is given as a date:

![iho-s53-1](https://github.com/relaton/relaton-data-iho/assets/33627611/b89631cf-0ad8-4098-a8c6-c580824910fd)

I understand that the edition number must have a format of: `a.b.c`
So, what edition number would correspond in this case?

A similar case also occurs for these publications: P-1-21, P-1-22, P-1, P-5, P-6
(In none of these documents the edition is given explicitly.)

**Comment by ronaldtse** [comment]
Yes the edition number is a.b.c. For these documents we must find out or ask IHO to provide their edition numbers.

**Comment by ronaldtse** [comment]
This is fixed in #26 .
