### ISSUE TITLE
Version numbers on IHO Document Archive

### ISSUE THREAD

**Issue by manuelfuenmayor** [relaton/relaton-data-iho#25]
*Issue found in https://github.com/relaton/relaton-data-iho/pull/23*
 
The [IHO Document Archive](https://iho-monaco.reisswolf.fit/login/auth) shows some metadata about the PDF file where a version number is indicated:

![iho-s53-2](https://github.com/relaton/relaton-data-iho/assets/33627611/835f7d85-44ae-47ec-8671-7d07b8c172eb)

But looking at other publications that do have explicit edition numbers, I've noticed that this "version number" is not always equal to them.
Does this version number correspond to the actual edition of the document?

**Comment by ronaldtse** [comment]
@manuelfuenmayor so there is supposed to only be an edition number. 

- if there is only a version number but no edition number, then we take the version number as the edition number. 
- if there are both edition and version numbers, then please file an issue for IHO to resolve it. 

Thanks!

**Comment by manuelfuenmayor** [comment]
> if there are both edition and version numbers, then please file an issue for IHO to resolve it.

@ronaldtse, what would be the IHO repository to file the issues?
