### ISSUE TITLE
Create GHA script to ensure all YAML files here can be resolved by Relaton

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-iho#8]
Need to create a GHA workflow to read all these YAML files and attempt to load them. Any failed YAML should be reported immediately.

**Comment by ronaldtse** [comment]
Maybe relaton-cli?

**Comment by andrew2net** [comment]
@ronaldtse yes, we can use relaton-cli, but we need to finish relaton-iho first.

**Comment by ronaldtse** [comment]
@andrew2net this repo is now fully ready -- can you help ensure these entries can be fetched?

**Comment by andrew2net** [comment]
@ronaldtse I'm finishing relaton-iho now. It needs relaton-bib refactoring and to release new relaton.

**Comment by andrew2net** [comment]
@ronaldtse the document `data/p-1.yaml` has missed `editorialgroup/workgroup` which is mandatory.

**Comment by ronaldtse** [comment]
Now in #11
